// shared/types/filters/panel/gallery.ts
/** The Galleries panel's rows, in the panel's order */
import type { GALLERY_FIELDS } from "../fields.js";
import { HAS_MODIFIERS, HAS_ONE_MODIFIERS, type PanelField } from "./types.js";

export const GALLERY_PANEL = [
  // Common
  {
    key: "title",
    field: "title",
    label: "Title Search",
    group: "common",
    editor: "text",
    placeholder: "Search title...",
  },
  {
    key: "performerIds",
    field: "performers",
    label: "Performers",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select performers...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "performerIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    countContext: "galleries",
  },
  {
    key: "studioIds",
    field: "studios",
    label: "Studios",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select studios...",
    modifiers: HAS_ONE_MODIFIERS,
    modifierKey: "studioIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    hierarchyKey: "studioIdsDepth",
    hierarchyLabel: "Include sub-studios",
    countContext: "galleries",
  },
  {
    key: "tagIds",
    field: "tags",
    label: "Tags",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select tags...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "tagIdsModifier",
    defaultModifier: "INCLUDES_ALL",
    modifierLabels: "has",
    hierarchyKey: "tagIdsDepth",
    hierarchyLabel: "Include sub-tags",
    countContext: "galleries",
    pinnedByDefault: true,
  },
  {
    key: "rating",
    field: "rating100",
    label: "Rating (0-100)",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 100 },
    pinnedByDefault: true,
  },
  {
    key: "imageCount",
    field: "image_count",
    label: "Image Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "tagCount",
    field: "tag_count",
    label: "Tag Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 50 },
  },
  {
    key: "favorite",
    field: "favorite",
    label: "Favorite Galleries",
    group: "common",
    editor: "toggle",
    placeholder: "Favorites Only",
  },
  {
    key: "hasFavoriteImage",
    field: "hasFavoriteImage",
    label: "Has Favorite Image",
    group: "common",
    editor: "toggle",
    placeholder: "Has at least one favorited image",
  },
] as const satisfies readonly PanelField<
  Extract<keyof typeof GALLERY_FIELDS, string>
>[];
