// shared/types/filters/panel/image.ts
/** The Images panel's rows, in the panel's order */
import type { IMAGE_FIELDS } from "../fields.js";
import { HAS_MODIFIERS, HAS_ONE_MODIFIERS, type PanelField } from "./types.js";

export const IMAGE_PANEL = [
  // Common
  {
    key: "performerIds",
    field: "performers",
    label: "Performers",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select performers...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "performerIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    countContext: "images",
    excludeKey: "performerIdsExclude",
  },
  {
    key: "studioIds",
    field: "studios",
    label: "Studios",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select studios...",
    modifiers: HAS_ONE_MODIFIERS,
    modifierKey: "studioIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    hierarchyKey: "studioIdsDepth",
    hierarchyLabel: "Include sub-studios",
    countContext: "images",
    excludeKey: "studioIdsExclude",
  },
  {
    key: "tagIds",
    field: "tags",
    label: "Tags",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select tags...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "tagIdsModifier",
    defaultModifier: "INCLUDES_ALL",
    modifierLabels: "has",
    hierarchyKey: "tagIdsDepth",
    hierarchyLabel: "Include sub-tags",
    countContext: "images",
    pinnedByDefault: true,
    excludeKey: "tagIdsExclude",
  },
  {
    key: "galleryIds",
    field: "galleries",
    label: "Galleries",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select galleries...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "galleryIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    countContext: "images",
  },
  {
    key: "rating",
    field: "rating100",
    label: "Rating (0-100)",
    group: "common",
    editor: "number",
    modifierKey: "ratingModifier",
    presenceLabels: { isNull: "Not rated", notNull: "Rated" },
    bounds: { min: 0, max: 100 },
    pinnedByDefault: true,
  },
  {
    key: "favorite",
    field: "favorite",
    label: "Favorite Images",
    group: "common",
    editor: "toggle",
    placeholder: "Favorites Only",
  },
  {
    key: "oCounter",
    field: "o_counter",
    label: "O Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "tagCount",
    field: "tag_count",
    label: "Tag Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 50 },
  },
] as const satisfies readonly PanelField<
  Extract<keyof typeof IMAGE_FIELDS, string>
>[];
