// shared/types/filters/panel/performer.ts
/** The Performers panel's rows, in the panel's order */
import type { PERFORMER_FIELDS } from "../fields.js";
import { HAS_MODIFIERS, type PanelField } from "./types.js";

export const PERFORMER_PANEL = [
  // Common
  {
    key: "name",
    field: "name",
    label: "Name Search",
    group: "common",
    editor: "text",
    placeholder: "Search name...",
  },
  {
    key: "tagIds",
    field: "tags",
    label: "Tags",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select tags...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "tagIdsModifier",
    defaultModifier: "INCLUDES_ALL",
    modifierLabels: "has",
    hierarchyKey: "tagIdsDepth",
    hierarchyLabel: "Include sub-tags",
    countContext: "performers",
    pinnedByDefault: true,
  },
  {
    key: "gender",
    field: "gender",
    label: "Gender",
    group: "common",
    editor: "enum",
    placeholder: "Any gender",
    choices: [
      { value: "MALE", label: "Male" },
      { value: "FEMALE", label: "Female" },
      { value: "TRANSGENDER_MALE", label: "Trans Male" },
      { value: "TRANSGENDER_FEMALE", label: "Trans Female" },
      { value: "INTERSEX", label: "Intersex" },
      { value: "NON_BINARY", label: "Non-Binary" },
    ],
    pinnedByDefault: true,
  },
  {
    key: "rating",
    field: "rating100",
    label: "Rating (0-100)",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 100 },
    pinnedByDefault: true,
  },
  {
    key: "oCounter",
    field: "o_counter",
    label: "O Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "sceneCount",
    field: "scene_count",
    label: "Scene Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "favorite",
    field: "favorite",
    label: "Favorite Performers",
    group: "common",
    editor: "toggle",
    placeholder: "Favorites Only",
  },

  // Dates
  {
    key: "age",
    field: "age",
    label: "Age",
    group: "dates",
    editor: "number",
    bounds: { min: 18, max: 100 },
  },
  {
    key: "birthYear",
    field: "birth_year",
    label: "Birth Year",
    group: "dates",
    editor: "number",
    bounds: { min: 1900, max: 2010 },
  },
  {
    key: "deathYear",
    field: "death_year",
    label: "Death Year",
    group: "dates",
    editor: "number",
    bounds: { min: 1900, max: 2100 },
  },
  {
    key: "careerLength",
    field: "career_length",
    label: "Career Length (years)",
    group: "dates",
    editor: "number",
    bounds: { min: 0, max: 50 },
    unit: "years",
  },
  {
    key: "birthdate",
    field: "birthdate",
    label: "Birth Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "deathDate",
    field: "death_date",
    label: "Death Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "createdAt",
    field: "created_at",
    label: "Created Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "updatedAt",
    field: "updated_at",
    label: "Updated Date",
    group: "dates",
    editor: "date",
  },

  // Attributes: hair, eyes, ethnicity and breast type are Stash free text,
  // offered as a select of the usual values
  {
    key: "hairColor",
    field: "hair_color",
    label: "Hair Color",
    group: "attributes",
    editor: "enum",
    placeholder: "Any hair color",
    choices: [
      { value: "BLONDE", label: "Blonde" },
      { value: "BRUNETTE", label: "Brunette" },
      { value: "BLACK", label: "Black" },
      { value: "RED", label: "Red" },
      { value: "AUBURN", label: "Auburn" },
      { value: "GREY", label: "Grey" },
      { value: "BALD", label: "Bald" },
      { value: "VARIOUS", label: "Various" },
      { value: "OTHER", label: "Other" },
    ],
  },
  {
    key: "eyeColor",
    field: "eye_color",
    label: "Eye Color",
    group: "attributes",
    editor: "enum",
    placeholder: "Any eye color",
    choices: [
      { value: "BROWN", label: "Brown" },
      { value: "BLUE", label: "Blue" },
      { value: "GREEN", label: "Green" },
      { value: "GREY", label: "Grey" },
      { value: "HAZEL", label: "Hazel" },
      { value: "OTHER", label: "Other" },
    ],
  },
  {
    key: "ethnicity",
    field: "ethnicity",
    label: "Ethnicity",
    group: "attributes",
    editor: "enum",
    placeholder: "Any ethnicity",
    choices: [
      { value: "CAUCASIAN", label: "Caucasian" },
      { value: "BLACK", label: "Black" },
      { value: "ASIAN", label: "Asian" },
      { value: "INDIAN", label: "Indian" },
      { value: "LATIN", label: "Latin" },
      { value: "MIDDLE_EASTERN", label: "Middle Eastern" },
      { value: "MIXED", label: "Mixed" },
      { value: "OTHER", label: "Other" },
    ],
  },
  {
    key: "fakeTits",
    field: "fake_tits",
    label: "Breast Type",
    group: "attributes",
    editor: "enum",
    placeholder: "Any",
    choices: [
      { value: "Fake", label: "Fake/Augmented" },
      { value: "Natural", label: "Natural" },
    ],
  },
  {
    key: "measurements",
    field: "measurements",
    label: "Measurements",
    group: "attributes",
    editor: "text",
    placeholder: "e.g. 34-24-34",
  },
  {
    key: "tattoos",
    field: "tattoos",
    label: "Tattoos",
    group: "attributes",
    editor: "text",
    placeholder: "Search tattoos...",
  },
  {
    key: "piercings",
    field: "piercings",
    label: "Piercings",
    group: "attributes",
    editor: "text",
    placeholder: "Search piercings...",
  },
  {
    key: "height",
    field: "height",
    label: "Height (cm)",
    group: "attributes",
    editor: "number",
    bounds: { min: 100, max: 250 },
    measure: "height",
  },
  {
    key: "weight",
    field: "weight",
    label: "Weight (kg)",
    group: "attributes",
    editor: "number",
    bounds: { min: 30, max: 200 },
    measure: "weight",
  },
  {
    key: "penisLength",
    field: "penis_length",
    label: "Penis Length (cm)",
    group: "attributes",
    editor: "number",
    bounds: { min: 0, max: 40 },
    measure: "length",
  },

  // Other
  {
    key: "playCount",
    field: "play_count",
    label: "Play Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "details",
    field: "details",
    label: "Details Search",
    group: "other",
    editor: "text",
    placeholder: "Search details...",
  },
] as const satisfies readonly PanelField<
  Extract<keyof typeof PERFORMER_FIELDS, string>
>[];
