// shared/types/filters/panel/scene.ts
/** The Scenes panel's rows, in the panel's order */
import { COMPARISON_MODIFIERS } from "../criteria.js";
import type { SCENE_FIELDS } from "../fields.js";
import {
  HAS_MODIFIERS,
  HAS_ONE_MODIFIERS,
  INCLUDES_ONLY,
  type PanelField,
} from "./types.js";

/** Stash's resolutions as its panel offers them: VR_HD left out */
const RESOLUTION_CHOICES = [
  { value: "VERY_LOW", label: "144p" },
  { value: "LOW", label: "240p" },
  { value: "R360P", label: "360p" },
  { value: "STANDARD", label: "480p" },
  { value: "WEB_HD", label: "540p" },
  { value: "STANDARD_HD", label: "720p" },
  { value: "FULL_HD", label: "1080p" },
  { value: "QUAD_HD", label: "1440p" },
  { value: "FOUR_K", label: "4K" },
  { value: "FIVE_K", label: "5K" },
  { value: "SIX_K", label: "6K" },
  { value: "SEVEN_K", label: "7K" },
  { value: "EIGHT_K", label: "8K" },
  { value: "HUGE", label: "Huge" },
] as const;

export const SCENE_PANEL = [
  // Common
  {
    key: "title",
    field: "title",
    label: "Title Search",
    group: "common",
    editor: "text",
    placeholder: "Search title...",
  },
  {
    key: "details",
    field: "details",
    label: "Details Search",
    group: "common",
    editor: "text",
    placeholder: "Search details...",
  },
  {
    key: "performerIds",
    field: "performers",
    label: "Performers",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select performers...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "performerIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "has",
    countContext: "scenes",
    pinnedByDefault: true,
  },
  {
    key: "studioId",
    field: "studios",
    label: "Studio",
    group: "common",
    editor: "ref",
    multi: false,
    placeholder: "Select studio...",
    modifiers: INCLUDES_ONLY,
    hierarchyKey: "studioIdDepth",
    hierarchyLabel: "Include sub-studios",
    countContext: "scenes",
  },
  {
    key: "tagIds",
    field: "tags",
    label: "Tags",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select tags...",
    modifiers: HAS_MODIFIERS,
    modifierKey: "tagIdsModifier",
    defaultModifier: "INCLUDES_ALL",
    modifierLabels: "has",
    hierarchyKey: "tagIdsDepth",
    hierarchyLabel: "Include sub-tags",
    countContext: "scenes",
    pinnedByDefault: true,
  },
  {
    key: "groupIds",
    field: "groups",
    label: "Collections",
    group: "common",
    editor: "ref",
    multi: true,
    placeholder: "Select collections...",
    modifiers: HAS_ONE_MODIFIERS,
    modifierKey: "groupIdsModifier",
    defaultModifier: "INCLUDES",
    modifierLabels: "in",
    countContext: "scenes",
  },
  {
    key: "rating",
    field: "rating100",
    label: "Rating (0-100)",
    group: "common",
    editor: "number",
    modifierKey: "ratingModifier",
    presenceLabels: { isNull: "Not rated", notNull: "Rated" },
    bounds: { min: 0, max: 100 },
    pinnedByDefault: true,
  },
  {
    key: "oCount",
    field: "o_counter",
    label: "O Count",
    group: "common",
    editor: "number",
    bounds: { min: 0, max: 300 },
  },
  {
    key: "duration",
    field: "duration",
    label: "Duration (minutes)",
    group: "common",
    editor: "number",
    bounds: { min: 1, max: 300 },
    scale: 60,
    unit: "minutes",
  },
  {
    key: "favorite",
    field: "favorite",
    label: "Favorite Scenes",
    group: "common",
    editor: "toggle",
    placeholder: "Favorites Only",
  },
  {
    key: "performerFavorite",
    field: "performer_favorite",
    label: "Favorite Performers",
    group: "common",
    editor: "toggle",
    placeholder: "Favorite Performers Only",
  },
  {
    key: "studioFavorite",
    field: "studio_favorite",
    label: "Favorite Studios",
    group: "common",
    editor: "toggle",
    placeholder: "Favorite Studios Only",
  },
  {
    key: "tagFavorite",
    field: "tag_favorite",
    label: "Favorite Tags",
    group: "common",
    editor: "toggle",
    placeholder: "Favorite Tags Only",
  },

  // Dates
  {
    key: "date",
    field: "date",
    label: "Scene Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "createdAt",
    field: "created_at",
    label: "Created Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "updatedAt",
    field: "updated_at",
    label: "Updated Date",
    group: "dates",
    editor: "date",
  },
  {
    key: "lastPlayedAt",
    field: "last_played_at",
    label: "Last Played Date",
    group: "dates",
    editor: "date",
  },

  // Video
  {
    key: "resolution",
    field: "resolution",
    label: "Resolution",
    group: "video",
    editor: "enum",
    placeholder: "Any resolution",
    choices: RESOLUTION_CHOICES,
    modifiers: COMPARISON_MODIFIERS,
    modifierKey: "resolutionModifier",
    defaultModifier: "EQUALS",
  },
  {
    key: "bitrate",
    field: "bitrate",
    label: "Bitrate (Mbps)",
    group: "video",
    editor: "number",
    bounds: { min: 0, max: 100 },
    scale: 1_000_000,
    unit: "Mbps",
  },
  {
    key: "framerate",
    field: "framerate",
    label: "Framerate (fps)",
    group: "video",
    editor: "number",
    bounds: { min: 0, max: 120 },
    unit: "fps",
  },
  {
    key: "orientation",
    field: "orientation",
    label: "Orientation",
    group: "video",
    editor: "enum",
    placeholder: "Any orientation",
    choices: [
      { value: "LANDSCAPE", label: "Landscape" },
      { value: "PORTRAIT", label: "Portrait" },
      { value: "SQUARE", label: "Square" },
    ],
  },
  {
    key: "videoCodec",
    field: "video_codec",
    label: "Video Codec",
    group: "video",
    editor: "text",
    placeholder: "e.g. h264, hevc",
  },
  {
    key: "audioCodec",
    field: "audio_codec",
    label: "Audio Codec",
    group: "video",
    editor: "text",
    placeholder: "e.g. aac, mp3",
  },

  // Other
  {
    key: "director",
    field: "director",
    label: "Director Search",
    group: "other",
    editor: "text",
    placeholder: "Search director...",
  },
  {
    key: "playDuration",
    field: "play_duration",
    label: "Play Duration (minutes)",
    group: "other",
    editor: "number",
    bounds: { min: 1, max: 300 },
    scale: 60,
    unit: "minutes",
  },
  {
    key: "playCount",
    field: "play_count",
    label: "Play Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 1000 },
  },
  {
    key: "performerCount",
    field: "performer_count",
    label: "Performer Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 20 },
  },
  {
    key: "performerAge",
    field: "performer_age",
    label: "Performer Age",
    group: "other",
    editor: "number",
    bounds: { min: 18, max: 100 },
  },
  {
    key: "tagCount",
    field: "tag_count",
    label: "Tag Count",
    group: "other",
    editor: "number",
    bounds: { min: 0, max: 50 },
  },
] as const satisfies readonly PanelField<
  Extract<keyof typeof SCENE_FIELDS, string>
>[];
