services:
  peek-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "${PEEK_BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      # These are ALWAYS the same inside Docker - no need in .env file
      - CONFIG_DIR=/app/data
      - STASH_MEDIA_PATH=/app/media
      - STASH_INTERNAL_PATH=/data
    volumes:
      # Hot reloading - mount source code
      - ./server:/app
      - /app/node_modules
      # Media access - configured via environment variables
      - ${MEDIA_VOLUME_CONFIG}
      # Peek config/data directory
      - ${PEEK_DATA_DIR:-./.peek-data}:/app/data
    networks:
      - peek-network

  peek-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "${PEEK_FRONTEND_PORT:-6969}:5173"
    volumes:
      # Hot reloading - mount source code
      - ./client:/app
      - /app/node_modules
    depends_on:
      - peek-server
    networks:
      - peek-network

networks:
  peek-network:
    driver: bridge

volumes:
  # SMB/CIFS volume (only used if MEDIA_VOLUME_CONFIG=media-share:/app/media)
  media-share:
    driver: local
    driver_opts:
      type: cifs
      device: "${SMB_SHARE}"
      o: "username=${SMB_USERNAME},password=${SMB_PASSWORD},uid=1000,gid=1000,iocharset=utf8,file_mode=0644,dir_mode=0755"
