services:
  peek-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "${PEEK_BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      # Config directory location inside container
      - CONFIG_DIR=/app/data
    volumes:
      # Hot reloading - mount source code
      - ./server:/app
      - /app/node_modules
      # Media access - multiple volumes for multi-library support
      - ${MEDIA_VOLUME_1:-peek-videos}:/app/media:ro
      - ${MEDIA_VOLUME_2:-peek-images}:/app/images:ro
      # Peek config/data directory
      - ${PEEK_DATA_DIR:-./.peek-data}:/app/data
    networks:
      - peek-network

  peek-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "${PEEK_FRONTEND_PORT:-6969}:5173"
    volumes:
      # Hot reloading - mount source code
      - ./client:/app
      - /app/node_modules
    depends_on:
      - peek-server
    networks:
      - peek-network

networks:
  peek-network:
    driver: bridge

volumes:
  # External Docker volumes (created separately, e.g., CIFS/SMB mounts)
  # Create with: docker volume create peek-videos --driver local --opt type=cifs ...
  peek-videos:
    external: true
  peek-images:
    external: true
