import js from "@eslint/js";
import vitest from "@vitest/eslint-plugin";
import globals from "globals";
import tseslint from "typescript-eslint";

const testFiles = ["tests/**/*.ts", "integration/**/*.ts"];

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "prisma/migrations/**",
      // Auto-generated by GraphQL codegen
      "graphql/generated/**",
      // Non-TypeScript scripts (not covered by tsconfig)
      "**/*.mjs",
      "**/*.js",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  {
    files: ["**/*.ts"],
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: "module",
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.node,
        NodeJS: "readonly",
      },
    },
    rules: {
      // --- Core rules from issue #465 (all error) ---
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",

      // A default does not excuse a missing union member, so a new entity
      // type cannot fall silently into it
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      // Raw SQL rows are typed as SQLite returns them (a COUNT or SUM is a
      // bigint, a BOOLEAN column a boolean), so a flagged Number() is dropped
      // only when the value's type is honest
      "@typescript-eslint/no-unnecessary-type-conversion": "error",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
      "@typescript-eslint/prefer-reduce-type-parameter": "error",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",

      // Ratcheted in eslint-suppressions.json, fixed by the PRs that own the
      // code: a `||` on a string or number (where "" or 0 can mean something,
      // such as "every instance"), and conditions that only become checkable
      // once rows are honestly typed. The counts may only fall.
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      "@typescript-eslint/no-unnecessary-condition": "error",

      // Not adopted. Prisma enums are string-literal unions, so TypeScript
      // already rejects a comparison with a non-member; the other is style.
      "@typescript-eslint/no-unsafe-enum-comparison": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",

      // The writer rule: every transaction is a dbWrite unit, so writers
      // queue in Node instead of starving each other inside the engine
      "no-restricted-syntax": [
        "error",
        {
          selector: 'MemberExpression[property.name="$transaction"]',
          message:
            "use dbWriteTransaction / dbWriteBatch (server-sql.md, Writes)",
        },
      ],
    },
  },
  // The one place that calls $transaction, and the tests that mock it
  {
    files: ["utils/dbWrite.ts", ...testFiles],
    rules: {
      "no-restricted-syntax": "off",
    },
  },
  // Tests: the source rules above, plus vitest's. tsconfig.json excludes
  // tests/ and integration/, so they are typed by tsconfig.tests.json.
  {
    files: testFiles,
    ...vitest.configs.recommended,
    languageOptions: {
      parserOptions: {
        projectService: false,
        project: ["./tsconfig.tests.json"],
      },
    },
    rules: {
      ...vitest.configs.recommended.rules,
      // vitest's version allows `expect(mock.method)`
      "@typescript-eslint/unbound-method": "off",
      "vitest/unbound-method": "error",
      // expect(value, "message")
      "vitest/valid-expect": ["error", { maxArgs: 2 }],
      // Helpers named expect* assert too
      "vitest/expect-expect": [
        "error",
        { assertFunctionNames: ["expect", "expect*"] },
      ],
      // Tests of the legacy scene path (USE_SQL_QUERY_BUILDER=false) call
      // it on purpose, until item 73 removes the path
      "@typescript-eslint/no-deprecated": [
        "error",
        {
          allow: [
            {
              from: "file",
              name: "getAllScenes",
              path: "services/StashEntityService.ts",
            },
          ],
        },
      ],
      "vitest/no-standalone-expect": [
        "error",
        {
          additionalTestBlockFunctions: [
            "beforeAll",
            "beforeEach",
            "afterEach",
            "afterAll",
          ],
        },
      ],
    },
  },
  // untrusted() and malformedRow() are the deliberate casts for invalid input:
  // their type parameter is the target type, used once by design.
  {
    files: ["tests/helpers/untrusted.ts"],
    rules: {
      "@typescript-eslint/no-unnecessary-type-parameters": "off",
    },
  }
);
