import js from "@eslint/js";
import vitest from "@vitest/eslint-plugin";
import globals from "globals";
import tseslint from "typescript-eslint";

const testFiles = ["tests/**/*.ts", "integration/**/*.ts"];

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "prisma/migrations/**",
      // Auto-generated by GraphQL codegen
      "graphql/generated/**",
      // Non-TypeScript scripts (not covered by tsconfig)
      "**/*.mjs",
      "**/*.js",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  {
    files: ["**/*.ts"],
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: "module",
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.node,
        NodeJS: "readonly",
      },
    },
    rules: {
      // --- Core rules from issue #465 (all error) ---
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",

      // --- Strict rules deferred to follow-up PRs ---
      // These are valid improvements but out of scope for #465.
      // no-unnecessary-condition: ~414 violations, mostly redundant null checks
      "@typescript-eslint/no-unnecessary-condition": "off",
      // no-unsafe-enum-comparison: ~218 violations, Prisma enum patterns
      "@typescript-eslint/no-unsafe-enum-comparison": "off",
      // Cosmetic/style rules — enable incrementally later
      "@typescript-eslint/no-unnecessary-type-conversion": "off",
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "off",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/prefer-reduce-type-parameter": "off",
    },
  },
  // Tests: the source rules above, plus vitest's. tsconfig.json excludes
  // tests/ and integration/, so they are typed by tsconfig.tests.json.
  {
    files: testFiles,
    ...vitest.configs.recommended,
    languageOptions: {
      parserOptions: {
        projectService: false,
        project: ["./tsconfig.tests.json"],
      },
    },
    rules: {
      ...vitest.configs.recommended.rules,
      // vitest's version allows `expect(mock.method)`
      "@typescript-eslint/unbound-method": "off",
      "vitest/unbound-method": "error",
      // expect(value, "message")
      "vitest/valid-expect": ["error", { maxArgs: 2 }],
      // Helpers named expect* assert too
      "vitest/expect-expect": [
        "error",
        { assertFunctionNames: ["expect", "expect*"] },
      ],
      // Tests of the legacy scene path (USE_SQL_QUERY_BUILDER=false) call
      // it on purpose, until item 73 removes the path
      "@typescript-eslint/no-deprecated": [
        "error",
        {
          allow: [
            {
              from: "file",
              name: "getAllScenes",
              path: "services/StashEntityService.ts",
            },
          ],
        },
      ],
      "vitest/no-standalone-expect": [
        "error",
        {
          additionalTestBlockFunctions: [
            "beforeAll",
            "beforeEach",
            "afterEach",
            "afterAll",
          ],
        },
      ],
    },
  },
  // untrusted() and malformedRow() are the deliberate casts for invalid input:
  // their type parameter is the target type, used once by design.
  {
    files: ["tests/helpers/untrusted.ts"],
    rules: {
      "@typescript-eslint/no-unnecessary-type-parameters": "off",
    },
  }
);
